apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://127.0.0.1:8443
    certificate-authority-data: <BASE64_ENCODED_CA_CERT>
users:
- name: minikube
  user:
    client-certificate-data: <BASE64_ENCODED_CLIENT_CERT>
    client-key-data: <BASE64_ENCODED_CLIENT_KEY>
contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
current-context: minikube
